import jsPDF from 'jspdf';
import { formatDate } from './formatDate';

export function generateReferralPDF(patient, screening, doctorName) {
  const doc = new jsPDF();
  const w = doc.internal.pageSize.width;

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, w, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('NirAmaya — REFERRAL', w / 2, 18, { align: 'center' });

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  let y = 45;

  const line = (label, value) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(String(value || '—'), 65, y);
    y += 8;
  };

  doc.setFont('helvetica', 'bold');
  doc.text('PATIENT DETAILS', 20, y); y += 10;

  line('Name', `${patient.name} | ${patient.age} | ${patient.gender}`);
  line('Village', patient.village);
  line('Phone', patient.phone);
  y += 4;

  doc.setFont('helvetica', 'bold');
  doc.text('CLINICAL FINDINGS', 20, y); y += 10;

  const v = screening.vitals || {};
  line('Blood Pressure', `${v.systolic}/${v.diastolic} mmHg`);
  line('Blood Sugar', `${v.bloodSugar} mg/dL`);
  line('BMI', v.bmi);
  y += 4;

  doc.setFont('helvetica', 'bold');
  doc.text('RISK ASSESSMENT', 20, y); y += 10;

  const r = screening.result || {};
  line('Risk Level', r.riskLevel);
  line('Risk Score', `${r.score}/20`);
  line('Flags', (r.flags || []).join(', '));
  y += 4;

  doc.setFont('helvetica', 'bold');
  doc.text('REFERRAL DETAILS', 20, y); y += 10;

  line('Referred By', doctorName);
  line('Date', formatDate(new Date()));

  doc.setDrawColor(200, 200, 200);
  doc.line(20, y + 5, w - 20, y + 5);
  y += 15;
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by NirAmaya — Rural Health Screening System', w / 2, y, { align: 'center' });

  doc.save(`referral-${patient.name.replace(/\s/g, '_')}.pdf`);
}
